### ISSUE TITLE
Implementing with lazy-loaded feature modules

### ISSUE THREAD

**Issue by KeirForster** [nilsmehlhorn/ngrx-wieder#21]
Hey @nilsmehlhorn!<br /><br />This library is awesome. I'm wondering how I go about implementing this across multiple lazy-loaded feature modules. Does the library support such a configuration like this:<br /><br />`StoreModule.forRoot(appReducer),`<br />`StoreModule.forFeature('feature-a', featureAReducers),`<br />`StoreModule.forFeature('feature-b', featureBReducers);`<br />`StoreModule.forFeature('feature-c', featureCReducers);`<br /><br />It seems that the provided example simply invokes the `undoRedo({ ... })` in the app reducer. Would I invoke `undoRedo({ undoActionType: 'UNDO_FEATURE_A', redoActionType: 'REDO_FEATURE_A',  })` in each featureReducer and modify the config?<br /><br />Second, having this functionality would appear to split the undoRedo patching into separate state slices, making a global undoRedo not possible or much more difficult to implement? This seems very similar to the `segmentationOverride` option in the config.<br /><br />I will experiment with some different configurations and report back. Any help is appreciated!

**Comment by nilsmehlhorn** [comment]
Hey @KeirForster thanks for your interest! It's definitely possible to use the library in lazy-loaded feature modules, however, spanning across multiple modules would be more difficult. I'll start with some context.

The `undoRedo()` function is just a configuration step that's required so that the `createUndoRedoReducer()` and `wrapReducer()` don't need a configuration in their signature - especially the former would otherwise be pretty different from the original `createReducer()`. But what you effectively get is just another reducer that under the hood will invoke your existing reducer for all actions except ones that are undo-redo specific (`'UNDO'`, `'BREAK_MERGE'` ...). So, basically the same considerations apply as when you'd try to combine multiple lazy-loaded feature reducers - that, to my knowledge, is not really possible. You'd have to combine them into one store feature. You could then still have two lazy-loaded Angular modules that both depend on a shared NgRx feature module though.

I developed this library for [SceneLab](https://app.scenelab.io/). There the feature module for the editor is actually lazy-loaded, but that's also the only part where you can undo-redo the state. The segmentation is used for having multiple tabs of the same state in the editor. Eventually though, all tabs reside inside the same reducer and this reducer is the only one that's wrapped by ngrx-wieder.

> Would I invoke undoRedo({ undoActionType: 'UNDO_FEATURE_A', redoActionType: 'REDO_FEATURE_A', }) in each featureReducer and modify the config?

Yes, you would do that, but you'd also have different undo-redo stacks per reducer then. Again, the segmentation is meant to facilitate multiple stacks for one reducer. What you seem to want is one stack for multiple reducers, right?

In theory, we could add another meta-reducer that'll fall out of `undoRedo()` which would be registered on a global level via `StoreModule.forRoot(reducers, { metaReducers: [undoRedoMetaReducer] }`. However, your custom reducers would then all work on an immer draft (though maybe we could configure exceptions along the lines of an existing `ActionReducerMap`). That's maybe not ideal but it could work - though I could be missing something, I'll think about it. Hope these explanations helped to clarify the situation. You still might want to think about whether you really need global undo-redo for your application or if you could restructure you state somehow.

**Comment by nilsmehlhorn** [comment]
I'll close this one for now. Lazy-loading in general shouldn't be a problem with this library. Also, undo-redo across multiple reducers should work by combining them (e.g. via [combineReducers](https://ngrx.io/api/store/combineReducers)) before applying the undo-redo meta reducer via the wrapping API. Lazily loading additional reducers into an existing history stack seems pretty abstract to me and I'm not sure whether that would actually make sense. Happy to continue the conversation with more info, possible use-cases and/or reproductions.
