### ISSUE TITLE
Feature Module it's not working

### ISSUE THREAD

**Issue by vm2geo** [nilsmehlhorn/ngrx-wieder#4]
I'm trying to use this library but the state it's not showing properly. I put in a feature module and did not work. Please can u help resolve this issue?

**Comment by nilsmehlhorn** [comment]
Can you provide more information or a reproduction on https://stackblitz.com/ or similar?

How are you integrating the library and what exactly is not working properly? Which versions of Angular, NgRx and ngrx-wieder are you using?

**Comment by vm2geo** [comment]
Here is the stackblitz example https://stackblitz.com/edit/angular-xqf5h9. Doing in the stackblitz worked, because i copied exactly like in your example. Maybe i was not seeing the error, but I noticed that you must use "mergeActionTypes" to work and not "allowedActionTypes", maybe i undestand wrong the documentation because english it's not my first language.

**Comment by nilsmehlhorn** [comment]
You need to put any actions that can be undone/redone into `allowedActionTypes`. You can then **also** put some of them into `mergeActionTypes` in order to undo/redo them in whole when actions of a single type occur directly after each other. A good example for this are sliders, have a look at the [example in the readme](https://github.com/nilsmehlhorn/ngrx-wieder#dealing-with-consecutive-changes).

Either way, all actions for undo/redo need to be in `allowedActionTypes`. Hope this is clear, otherwise don't hesitate to ask again.

I would be nice if you could give this library a star when it's working for you :)

**Comment by vm2geo** [comment]
Ok, that was exactly the problem, i wasn't passing the initial state to the reducer. And passing the initial state i was able to use the ```allowedActionTypes```. Thanks for this library, worked perfectly in my project that uses OpenLayers, i was able to undo and redo the zoom and the center of the map

**Comment by nilsmehlhorn** [comment]
Great to here that it worked out! I'll soon update the library to be in line with the new ngrx functions like `createReducer`. Some things changed with the new NgRx version and I'll have to see how to deal with that.

Sounds like a cool use-case, your welcome to share a link once it's public. This way people can see some examples of the library in action.
